Update BGPFilter docs
tigera/docs pull request #1064
Opened 2023-11-01 20:51 UTC by mazdakn

Product Version(s):

Issue:

Link to docs preview:

SME review:
- [ ] An SME has approved this change. 

DOCS review:
- [ ] A member of the docs team has approved this change.

Additional information:

Merge checklist:

- [ ] Deploy preview inspected wherever changes were made 
- [ ] Build completed successfully
- [ ] Test have passed

2023-11-06 11:48 UTC, ctauchen reviewed
Just a few line edits. 

Would this benefit from a technical review from someone else on your team?

Should this not also go into OSS 3.26? Or perhaps it doesn't belong in CE 3.17?

2023-11-06 11:48 UTC, ctauchen commented on calico-enterprise/reference/resources/felixconfig.mdx
> +| wireguardInterfaceName             | Name of the IPv4 WireGuard interface created by Felix. If you change the name, and want to clean up the previously-configured interface names on each node, this
```suggestion
| wireguardInterfaceName             | Name of the IPv4 WireGuard interface created by Felix. If you change the name and want to clean up the previously configured interface names on each node, this is a manual process. Felix expects the name to end with either .cali or .calico suffix.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          | string                                                                                                  | string                                  | wireguard.cali                                                                                                                                                                                                                                                                                                                                                                                                                                    |
```

2023-11-06 11:48 UTC, ctauchen commented on calico-enterprise/reference/resources/felixconfig.mdx
> +| wireguardInterfaceNameV6           | Name of the IPv6 WireGuard interface created by Felix. If you change the name, and want to clean up the previously-configured interface names on each node, this
```suggestion
| wireguardInterfaceNameV6           | Name of the IPv6 WireGuard interface created by Felix. If you change the name and want to clean up the previously configured interface names on each node, this is a manual process. Felix expects the name to end with either .cali or .calico suffix.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    | string                                                                                                  | string                                  | wg-v6.cali                                                                                                                                                                                                                                                                                                                                                                                                                                        |
```

2023-11-06 11:48 UTC, ctauchen commented on calico-enterprise/reference/resources/felixconfig.mdx
> +| wireguardInterfaceName             | Name of the IPv4 WireGuard interface created by Felix. If you change the name, and want to clean up the previously-configured interface names on each node, this
change globally

2023-11-06 11:48 UTC, ctauchen commented on calico-enterprise/reference/resources/felixconfig.mdx
> +| wireguardInterfaceNameV6           | Name of the IPv6 WireGuard interface created by Felix. If you change the name, and want to clean up the previously-configured interface names on each node, this
change globally

2023-11-06 18:10 UTC, mazdakn commented
@ctauchen we back ported the addition of `source` field to EE v3.18 and v3.17, but not to OSS since it is not needed.

2023-11-06 18:12 UTC, mazdakn commented
It's always good to get another review, but this is a small change all about adding two new fields.
At this point only @fasaxc know about it. Hopefully he has time to review this.

2023-11-10 15:03 UTC, fasaxc requested changes, later dismissed
Couple of minor points.  I think this covers the spec of the new field but I'm worried that users won't know that they should use these fields in most scenarios to get good behaviour.

I think the feature should be put into OS v3.27 but no need to backport (and code should be merged before adding that to the docs IMO).

2023-11-10 15:03 UTC, fasaxc commented on calico-enterprise/reference/resources/bgpfilter.mdx
> +| action        | Action to be taken for this rulw          | `Accept` or `Reject`                                       | string |         |
```suggestion
| action        | Action to be taken for this rule          | `Accept` or `Reject`                                       | string |         |
```

2023-11-10 15:03 UTC, fasaxc commented on calico-enterprise/reference/resources/bgpfilter.mdx
> +| interface     | String to match interface names           | A valid pattern to match interfaces                        | string |         |
What is the format of the pattern.   Maybe as simple as saying "`*` can be used as a wildcard"

2023-11-10 15:03 UTC, fasaxc commented on calico-enterprise/reference/resources/bgpfilter.mdx
> +| action        | Action to be taken for this rulw          | `Accept` or `Reject`                                       | string |         |
```suggestion
| action        | Action to be taken for this rule          | `Accept` or `Reject`                                       | string |         |
```

2023-11-10 16:25 UTC, ctauchen commented
@mazdakn While you're making changes, try fetching from upstream and rebasing. I think your build error may be related to a fix we got in last week.

2023-11-10 22:01 UTC, mazdakn commented
@fasaxc thanks for the review. The code is already merged into master which will be part of v3.27.

2023-11-15 17:16 UTC, merged