extended commentary on waf disable
tigera/docs pull request #1237
Opened 2024-01-10 21:07 UTC by electricjesus

Added some needed commentary on how the Application Layer CR works

Product Version(s):

Calico Enterprise, Calico Cloud

Issue:

https://tigera.atlassian.net/browse/RS-1440

Link to docs preview:

SME review:
- [x] An SME has approved this change. 

DOCS review:
- [ ] A member of the docs team has approved this change.

Additional information:

Merge checklist:

- [ ] Deploy preview inspected wherever changes were made 
- [ ] Build completed successfully
- [ ] Test have passed

2024-01-10 21:53 UTC, bmckercher123 commented on calico-enterprise/threat/web-application-firewall.mdx
> +[ApplicationLayer Specification](../reference/installation/api#operator.tigera.io/v1.ApplicationLayerSpec) can specify configuration for [Application Logging](../reference/installation/api#operator.t
### 
```suggestion
The [ApplicationLayer Specification](../reference/installation/api#operator.tigera.io/v1.ApplicationLayerSpec) can specify configuration for [Application Logging](../reference/installation/api#operator.tigera.io/v1.LogCollectionSpec) and [Application Layer Policy](../reference/installation/api#operator.tigera.io/v1.ApplicationLayerPolicyStatusType) as well. However, for this custom resource to be valid, at least one of these features must be enabled, for example:
```

2024-01-10 21:54 UTC, bmckercher123 commented on calico-enterprise/threat/web-application-firewall.mdx
> +Example: WAF enabled, ALP disabled -- this is valid
```suggestion
Valid example: WAF enabled, ALP disabled 
```

2024-01-10 21:56 UTC, bmckercher123 commented on calico-enterprise/threat/web-application-firewall.mdx
> +Example: WAF and ALP both set as disabled, log collection is omitted but the default is disabled -- this is invalid
```suggestion
Invalid example: WAF and ALP are both set as disabled, and log collection is omitted but the default is disabled
```

2024-01-10 22:28 UTC, bmckercher123 commented on calico-enterprise/threat/web-application-firewall.mdx
>  ### Disable WAF feature from your cluster
### Disable WAF feature from your cluster

To safely disable WAF, determine how to handle ApplicationLayer features and follow the steps:

- **Disable all ApplicationLayer features**

   You must delete the ApplcationLayer CR `tigera-secure`, for example:

    `kubectl delete applicationlayer tigera-secure`


- **Keep some ApplicationLayer features enabled**

To disable WAF, but keep some ApplicationLayer features enabled, you must update the [ApplicationLayer](../reference/installation/api#operator.tigera.io/v1.ApplicationLayer). Note that the [ApplicationLayer Specification](../reference/installation/api#operator.tigera.io/v1.ApplicationLayerSpec) can specify configuration for both [Application Logging](../reference/installation/api#operator.tigera.io/v1.LogCollectionSpec) and [Application Layer Policy](../reference/installation/api#operator.tigera.io/v1.ApplicationLayerPolicyStatusType). 

For the ApplicationLayer custom resource to be valid, at least one of these features must be enabled, for example:

**Valid YAML**

WAF is enabled, and is ALP disabled.

```yaml
apiVersion: operator.tigera.io/v1
kind: ApplicationLayer
metadata:
  name: tigera-secure
spec:
  webApplicationFirewall: Disabled
  applicationLayerPolicy: Enabled
```

**Invalid YAML**

WAF and ALP are disabled, and log collection is omitted (and the default is disabled). 

```yaml
apiVersion: operator.tigera.io/v1
kind: ApplicationLayer
metadata:
  name: tigera-secure
spec:
  webApplicationFirewall: Disabled
  applicationLayerPolicy: Disabled
```

2024-01-10 22:29 UTC, bmckercher123 requested changes
I had trouble following the choices. Suggestions for clarity (if my interpretation is correct).

2024-01-11 15:55 UTC, bmckercher123 approved these changes
An error on my part....delete the comma after WAF in this sentence. Otherwise, LTGM and go ahead and copy. 

To disable WAF, but

2024-01-11 20:01 UTC, bmckercher123 approved these changes
LGTM. Do a rebase and I'll merge it.

2024-01-11 21:23 UTC, bmckercher123 commented
You'll need to fix this link to build successfully: https://github.com/tigera/docs/reference/installation/api#operator.tigera.io/v1.ApplicationLayer

2024-02-27 23:19 UTC, ctauchen commented
@electricjesus Checking in on this. Looks like you were mostly there. Are you still hoping to merge this? Needs picks to new versions we've cut since you last worked on this.

2024-03-13 16:14 UTC, ctauchen commented
@electricjesus Closing this for now, please reopen if you want to revisit this material.

2024-03-27 09:56 UTC, peterkellydev commented
This is definitely needed. I am reopening this to get it over the line.

2024-03-28 09:03 UTC, ctauchen commented
@peterkellydev Sure thing. @electricjesus I think all that's needed is:

* add to new versions 
* rebase, sort conflicts

After that we should be good to go.

2024-04-08 16:55 UTC, ctauchen commented
LGTM

2024-04-08 16:55 UTC, merged