Update EGW docs
tigera/docs pull request #211
Opened 2023-01-17 23:47 UTC by sridhartigera

2023-01-26 14:04 UTC, fasaxc requested changes

2023-01-26 14:04 UTC, fasaxc commented on calico-enterprise/networking/egress/egress-gateway-aws.mdx
>  - Ensure that the policy sync API is enabled; this is required by egress gateway images starting with v3.11.0. To
Does operator not do this automatically when there's an EGW?  It could/should, I think

2023-01-26 14:04 UTC, fasaxc commented on calico-enterprise/networking/egress/egress-gateway-aws.mdx
> +- When upgrading, create an egress gateway as mentioned [above](#deploy-a-group-of-egress-gateways) which exactly matches
Think you need to be explicit here:
> When upgrading from a pre-v3.16 release, no automatic upgrade will occur. To upgrade a pre-v3.16 Egress Gateway deployment, create an equivalent EgressGateway resource with the same namespace and the same name; the operator will then take over management of the old `Deployment` resource, replacing it with the upgraded version.

2023-01-26 14:04 UTC, fasaxc commented on calico-enterprise/networking/egress/egress-gateway-maintenance.mdx
> +```yaml
Do we have a policy of not providing the `kubectl` command any more?

2023-01-26 14:04 UTC, fasaxc commented on calico-enterprise/networking/egress/egress-gateway-maintenance.mdx
> +```yaml
Worth a note here saying: note that this assumes that you have upgraded your Egress Gateways to use the new managed resource in v3.16 or above.

2023-01-26 14:04 UTC, fasaxc commented on calico-enterprise/networking/egress/egress-gateway-aws.mdx
> +- The labels are arbitrary. You can choose whatever names and values are convenient for your cluster's Namespaces and Pods to refer to in their egress selectors.
Should we also link to the operator reference docs for the EGW resource?

2023-01-27 02:46 UTC, sridhartigera commented on calico-enterprise/networking/egress/egress-gateway-aws.mdx
>  - Ensure that the policy sync API is enabled; this is required by egress gateway images starting with v3.11.0. To
At present, operator doesn't do this. Will target for 3.16 GA.

2023-01-27 11:07 UTC, fasaxc approved these changes, later dismissed

2023-02-01 17:10 UTC, merged