DOCS-1312: Fix Redirects
tigera/docs pull request #431
Opened 2023-03-05 16:49 UTC by girishshankaran

Fixes https://tigera.atlassian.net/browse/DOCS-1312

2023-03-06 05:43 UTC, girishshankaran commented
@doucol Can you review this one?

2023-03-06 16:09 UTC, doucol requested changes
Same as other PR - you will likely need a force redirect here (301!)

Also, do you think you could simplify all of these with a smaller set of directives? Such as:
/archive/v3.22/* https://docs.tigera.io/archive/v3.22/:splat 301!
/archive/v3.23/* https://docs.tigera.io/archive/v3.23/:splat 301!

2023-03-07 07:50 UTC, girishshankaran commented
> https://deploy-preview-431--calico-tigera.netlify.app

@doucol We already have these directives in the list:
/archive/v3.23/* https://docs.tigera.io/archive/v3.23/:splat 301
/archive/v3.22/* https://docs.tigera.io/archive/v3.22/:splat 301
/archive/v3.21/* https://docs.tigera.io/archive/v3.21/:splat 301
/archive/v3.20/* https://docs.tigera.io/archive/v3.20/:splat 301

These directives seem to cover the entire list that I added. Therefore, I removed my list and added "!"to the following list:
/archive/v3.23/* https://docs.tigera.io/archive/v3.23/:splat 301!
/archive/v3.22/* https://docs.tigera.io/archive/v3.22/:splat 301!
/archive/v3.21/* https://docs.tigera.io/archive/v3.21/:splat 301!
/archive/v3.20/* https://docs.tigera.io/archive/v3.20/:splat 301!

2023-03-07 12:52 UTC, ctauchen approved these changes
One error, otherwise LGTM. Please merge after tests confirm these are cleared.

2023-03-07 12:52 UTC, ctauchen commented on _redirects
> +/archive/v3.24/security/tutorials/kubernetes-policy-demo/kubernetes-demo      https://docs.tigera.io/archive/v3.24/security/tutorials/kubernetes-policy-demo/kubernetes-demo      391!
s/391/301

2023-03-07 12:54 UTC, ctauchen commented
> Same as other PR - you will likely need a force redirect here (301!)
> 
> Also, do you think you could simplify all of these with a smaller set of directives? Such as: /archive/v3.22/* https://docs.tigera.io/archive/v3.22/:splat 301! /archive/v3.23/* https://docs.tigera.io/archive/v3.23/:splat 301!

We've got a cascade of rules, now in three layers:

1) The new page-specific redirects from SEO list
2) The directory-specific 200 proxy rules to maintain old URL manifest links (which were generally close enough, and which we're now refining)
3) The blanket 301 redirects to send all other old-docs traffic to the proxy locations under docs.tigera.io.

2023-03-07 13:21 UTC, merged