Remove alert forwarding not supported note in enterprise doc
tigera/docs pull request #432
Opened 2023-03-05 18:15 UTC by hjiawei

This changeset removes alerts forwarding not supported notes in Calico Enterprise v3.15 and v3.16 docs. Calico Enterprise do support alert forwarding. It also reformats `README.md`.

2023-03-06 19:28 UTC, matthewdupre submitted a review, later dismissed

2023-03-06 20:11 UTC, bmckercher123 approved these changes
Approved, but copy to 3.16 and 3.17 docs. And fix in CC 3.15/3.16 docs.

2023-03-06 20:15 UTC, bmckercher123 requested changes
Copy to appropriate products/versions.

2023-03-06 20:24 UTC, hjiawei commented
> Approved, but copy to 3.16 and 3.17 docs.

@bmckercher123 The root level docs (3.16/3.17) is also modified. I have updated the description to reflect this.

2023-03-06 20:32 UTC, bmckercher123 commented
You'll need to update CC doc for 3.15/3.16.

2023-03-07 02:17 UTC, hjiawei commented
> @hjiawei You'll need to update CC doc for 3.15/3.16.

CC docs are also updated.

2023-03-07 16:02 UTC, bmckercher123 approved these changes
LGTM

2023-03-07 16:03 UTC, merged