Docs changes for adding IPTABLES_BACKEND to EGW deployment.
tigera/docs pull request #592
Opened 2023-04-25 19:26 UTC by sridhartigera

Product Version(s):

Issue:

Link to docs preview:

SME review:
- [ ] An SME has approved this change. 

DOCS review:
- [ ] A member of the docs team has approved this change.

Additional information:

2023-04-27 05:52 UTC, girishshankaran approved these changes
LGTM

2023-04-27 12:53 UTC, ctauchen commented
@sridhartigera Can you provide more context for this? A link to an issue? Is this associated with a release?

2023-04-27 13:20 UTC, sridhartigera commented
> @sridhartigera Can you provide more context for this? A link to an issue? Is this associated with a release?

@ctauchen Link to the issue https://tigera.atlassian.net/browse/CI-1226. This should go in as part of the next patch release for 3.15.2

2023-05-04 14:33 UTC, fasaxc commented on calico-enterprise_versioned_docs/version-3.15/networking/egress/egress-gateway-aws.mdx
> +          value: "nft"
We shouldn't default to `nft` in the docs.  Users will copy-paste without checking every flag is correct.  Better to have optional parameters commented out in some fashion, I think.

2023-05-04 14:34 UTC, fasaxc commented
If you address my comment, any reason this couldn't go in without a release?  The env var has existed for a long time, we just didn't document it.

2023-05-04 14:35 UTC, fasaxc commented on calico-enterprise_versioned_docs/version-3.15/networking/egress/egress-gateway-aws.mdx
> +          value: "nft"
Worth saying "for example on RHEL 9" or something for when you might want to use nft.

2023-05-04 15:17 UTC, fasaxc requested changes, later dismissed
One nit but I don't need to re-review.

2023-05-04 15:17 UTC, fasaxc commented on calico-enterprise_versioned_docs/version-3.15/networking/egress/egress-gateway-aws.mdx
> +          #value: "legacy"
```suggestion
        #  value: "legacy"
```
Think this'd look cleaner

2023-05-04 15:17 UTC, fasaxc commented on calico-enterprise_versioned_docs/version-3.15/networking/egress/egress-gateway-on-prem.mdx
> +          #value: "legacy"
```suggestion
        #  value: "legacy"
```

2023-05-05 09:44 UTC, merged