DOCS-1427: Fix yaml errors in the bash code block
tigera/docs pull request #607
Opened 2023-05-01 12:11 UTC by girishshankaran

Product Version(s):

Issue:
https://tigera.atlassian.net/browse/DOCS-1428
https://tigera.atlassian.net/browse/DOCS-1429

Link to docs preview:

SME review:
- [ ] An SME has approved this change. 

DOCS review:
- [ ] A member of the docs team has approved this change.

Additional information:

2023-05-01 17:00 UTC, doucol commented
@girishshankaran please recheck all the noValidation tags in here - i'd like to understand each one. I don't want to apply noValidation without it really being necessary. In some cases, it may be hiding actual yaml problems and in other cases, I think it could hide other errors that need to be fixed - like leftover liquid syntax from jekyll!

2023-05-01 17:01 UTC, doucol requested changes

2023-05-01 17:01 UTC, doucol commented on calico-cloud/reference/host-endpoints/connectivity.mdx
> +```bash noValidation
Why are we adding noValidation to this one?

2023-05-01 17:01 UTC, doucol commented on calico_versioned_docs/version-3.25/getting-started/kubernetes/openshift/installation.mdx
> +```bash noValidation
Why are we adding noValidation to this one?

2023-05-01 17:01 UTC, doucol commented on calico_versioned_docs/version-3.24/getting-started/kubernetes/openshift/installation.mdx
> +```bash noValidation
Why are we adding noValidation to this one?

2023-05-02 06:23 UTC, girishshankaran commented
> @girishshankaran please recheck all the noValidation tags in here - i'd like to understand each one. I don't want to apply noValidation without it really being necessary. In some cases, it may be hiding actual yaml problems and in other cases, I think it could hide other errors that need to be fixed - like leftover liquid syntax from jekyll!

Sure Doug. The `noValidation` tag is a temporary one. I may or may not keep it.

2023-05-02 06:49 UTC, girishshankaran commented on calico-cloud/reference/host-endpoints/connectivity.mdx
> +```bash noValidation
I'm able to fix this one. However, it's not a direct fix by adjusting the indentation or by adding a comment. To fix this one, I have to make a bit of structural changes as below. I would like someone to review these changes to be included in the docs.

```
- apiVersion: projectcalico.org/v3
  kind: GlobalNetworkPolicy
  metadata:
    name: failsafe
  - apiVersion: projectcalico.org/v3
  kind: GlobalNetworkPolicy
  metadata:
    name: failsafe
  spec:
    selector: "all()"
    order: 0
    ingress:
      - action: Allow
        protocol: TCP
        source:
          nets:
            - "<your management CIDR>"
        destination:
          ports: [22]
      - action: Allow
        protocol: ICMP
    egress:
      - action: Allow
        protocol: TCP
        destination:
          nets:
            - "<your etcd IP>/32"
            - "<your Kubernetes apiserver IP" **//changes here**
          ports: [<your etcd ports>, "<your Kubernetes apiserver IP ports>"] /**/changes here**
      - action: Allow
        protocol: UDP
        destination:
          ports: [67]
```

2023-05-02 07:12 UTC, girishshankaran commented on calico_versioned_docs/version-3.25/getting-started/kubernetes/openshift/installation.mdx
> +```bash noValidation
It's a valid yaml block. However, the validator is throwing errors because of the liquid syntax.

2023-05-02 07:19 UTC, girishshankaran commented on calico_versioned_docs/version-3.24/getting-started/kubernetes/openshift/installation.mdx
> +```bash noValidation
It's a valid yaml block. However, the validation is throwing errors because of the liquid syntax.

2023-05-04 04:39 UTC, girishshankaran commented on calico-cloud/reference/host-endpoints/connectivity.mdx
> +```bash noValidation
@doucol Are you okay with these changes I made in the yaml block?

2023-05-04 04:41 UTC, girishshankaran commented on calico_versioned_docs/version-3.25/getting-started/kubernetes/openshift/installation.mdx
> +```bash noValidation
Shall I retain the `noValidation` tag here?

2023-05-04 12:47 UTC, doucol commented on calico_versioned_docs/version-3.24/getting-started/kubernetes/openshift/installation.mdx
> +```bash noValidation
Can you fix the liquid syntax?

2023-05-04 12:58 UTC, doucol requested changes

2023-05-04 12:58 UTC, doucol commented on calico_versioned_docs/version-3.25/getting-started/kubernetes/openshift/installation.mdx
> +```bash noValidation
Ideally, we would fix replace the liquid syntax with whatever is appropriate here. If you don't feel comfortable doing this, just leave the noValidation tag and merge it. Then let me know and I'll take a look at it. Thanks

2023-05-04 15:41 UTC, doucol commented on calico-cloud/reference/host-endpoints/connectivity.mdx
> +```bash noValidation
Ok - here is how I think the "egress" object should look:
```
    egress:
      - action: Allow
        protocol: TCP
        destination:
          nets: [<your etcd IP>/32]
          ports: [<your etcd ports>]
      - action: Allow
        protocol: TCP
        destination:
          nets: [<your Kubernetes apiserver IP]
          ports: [<your Kubernetes apiserver IP ports>]
      - action: Allow
        protocol: UDP
        destination:
          ports: [67]
```

2023-05-05 06:01 UTC, girishshankaran commented on calico-cloud/reference/host-endpoints/connectivity.mdx
> +```bash noValidation
Thanks Doug. It's looking great. Our test did not throw any error.

2023-05-05 06:03 UTC, girishshankaran commented on calico_versioned_docs/version-3.25/getting-started/kubernetes/openshift/installation.mdx
> +```bash noValidation
I'll leave the `noValidation` tag and merge.

2023-05-05 06:03 UTC, girishshankaran commented on calico_versioned_docs/version-3.24/getting-started/kubernetes/openshift/installation.mdx
> +```bash noValidation
Same comment as above,

2023-05-05 10:18 UTC, ctauchen commented on calico_versioned_docs/version-3.25/getting-started/kubernetes/openshift/installation.mdx
> +```bash noValidation
@girishshankaran see https://github.com/tigera/docs/pull/627/files
You'll likely have a merge conflict to resolve when you rebase. But you can remove the novalidation tag.

2023-05-05 10:19 UTC, ctauchen commented on calico_versioned_docs/version-3.25/getting-started/kubernetes/openshift/installation.mdx
> +```bash noValidation
This one got fixed early in the migration process, but when we brought in 3.25 directly from the source, the fix that had been made in next and 3.24 got missed.

2023-05-05 10:22 UTC, girishshankaran commented on calico_versioned_docs/version-3.25/getting-started/kubernetes/openshift/installation.mdx
> +```bash noValidation
Sure Chris. I'll go ahead and remove the `noValidation` tag.

2023-05-05 10:24 UTC, girishshankaran commented on calico_versioned_docs/version-3.25/getting-started/kubernetes/openshift/installation.mdx
> +```bash noValidation
I'll address merge conflicts if there are any.

2023-05-05 11:45 UTC, girishshankaran commented on calico_versioned_docs/version-3.25/getting-started/kubernetes/openshift/installation.mdx
> +```bash noValidation
Removed the tag.

2023-05-05 15:13 UTC, ctauchen reviewed
One question!

2023-05-05 15:13 UTC, ctauchen commented on calico-enterprise_versioned_docs/version-3.16/reference/host-endpoints/connectivity.mdx
>  - apiVersion: projectcalico.org/v3
Is this one passing the test? I get the feeling that the hyphen that starts the first line of the YAML isn't right.

2023-05-08 16:04 UTC, doucol approved these changes

2023-05-08 16:11 UTC, merged