Added proxy config for CE 3.14, 3.13, 3.12
tigera/docs pull request #72
Opened 2022-11-15 22:23 UTC by ctauchen

This adds proxy configurations for CE 3.14, 3.13, and 3.12.

All of our old docs sites are to follow this model. `netlify.toml` will contain proxy definitions for every Jekyll site we want to continue serving in our docs portal.

2022-11-15 22:52 UTC, ctauchen commented
A note: The proxies are working correctly. But the JS files aren't loading. According to @penkeysuresh, may have something to do with `baseURL` in old docs.

2022-11-16 11:52 UTC, doucol approved these changes

2022-11-16 12:14 UTC, doucol requested changes

2022-11-16 12:14 UTC, doucol commented on Makefile
> +	cp _redirects build/_redirects
If you put the _redirects file into /static, it will get copied for you automatically

2022-11-16 12:22 UTC, ctauchen commented on Makefile
> +	cp _redirects build/_redirects
That sounds much more dependable. Will change, thanks!

2022-11-16 13:33 UTC, ctauchen commented
Closing and moving changes to https://github.com/tigera/docs/pull/74/

2022-11-16 13:33 UTC, closed without merging

2022-11-16 15:40 UTC, doucol approved these changes