Modifies Makefile to allow caching
tigera/docs pull request #754
Opened 2023-06-20 19:38 UTC by ctauchen

Trying to increase Netlify build times. Removes 'yarn clean' from build command. Hopefully allows cache to speed things up.

Product Version(s):

Issue:

Link to docs preview:

SME review:
- [ ] An SME has approved this change. 

DOCS review:
- [ ] A member of the docs team has approved this change.

Additional information:

Merge checklist:

- [ ] Deploy preview inspected wherever changes were made 
- [ ] Build completed successfully
- [ ] Test have passed

2023-06-20 19:38 UTC, ctauchen commented
@doucol Will this do it?

2023-06-20 21:30 UTC, doucol requested changes

2023-06-20 21:30 UTC, doucol commented on Makefile
> +all: build run-update-cloud-image-list test
yeah, that would do it, but I would probably create a new target called 'netlify' which does this and keep all as-is

2023-06-21 11:08 UTC, ctauchen commented on Makefile
> +all: build run-update-cloud-image-list test
Good suggestion -- changes made.

2023-06-21 13:21 UTC, doucol approved these changes

2023-06-21 13:29 UTC, merged