fix VPP ipsec docs & add troubleshooting info
tigera/docs pull request #774
Opened 2023-06-26 12:39 UTC by sknat

Product Version(s):

Issue:

Link to docs preview:

SME review:
- [x] An SME has approved this change. 

DOCS review:
- [x] A member of the docs team has approved this change.

Additional information:

Merge checklist:

- [x] Deploy preview inspected wherever changes were made 
- [x] Build completed successfully
- [x] Test have passed

2023-06-26 14:43 UTC, bmckercher123 commented on calico/getting-started/kubernetes/vpp/ipsec.mdx
> +To enable IPsec, you need first need to enable the ipsec feature in the `calico-vpp-config` ConfigMap.
```suggestion
To enable IPsec, you first need to enable the ipsec feature in the `calico-vpp-config` ConfigMap.
```

2023-06-26 14:43 UTC, bmckercher123 commented on calico/getting-started/kubernetes/vpp/ipsec.mdx
> +As an example on a three node cluster
```suggestion
As an example on a three-node cluster
```

2023-06-26 14:45 UTC, bmckercher123 requested changes
Thanks for your contributions to VPP docs. A few nit edits, then we'll need to get a Dev review.

2023-07-04 14:37 UTC, onong commented
CC @lwr20

2023-07-13 15:07 UTC, sknat commented
Thanks @bmckercher123 for the review 
and sorry for the delayed reply.

Just updated the PR with your suggested edits

2023-07-25 16:21 UTC, bmckercher123 approved these changes
Approved.

2023-07-25 17:08 UTC, merged