[DOCS-623] Partials - auto-hostendpoints-migrate
tigera/docs pull request #8
Opened 2022-08-26 21:19 UTC by denis-alkhelali

2022-08-29 09:04 UTC, alexeymagdich-tigera submitted a review, later dismissed

2022-08-29 19:47 UTC, alexeymagdich-tigera approved these changes, later dismissed

2022-08-29 20:52 UTC, doucol requested changes
Please convert the <code> blocks to <CodeBlock>

2022-08-29 20:52 UTC, doucol commented on src/components/partials/auto-hostendpoints-migrate.js
> +                    </code></pre>
Is there a way to specify what kind of code block it is? Is there a docusaurus version of the codeblock we should be using here?

2022-08-29 20:52 UTC, doucol commented on src/components/partials/auto-hostendpoints-migrate.js
> +                    </code></pre>
@denis-alkhelali I think you need to use this => 'import CodeBlock from "@theme/CodeBlock";'

2022-08-29 20:54 UTC, denis-alkhelali commented on src/components/partials/auto-hostendpoints-migrate.js
> +                    </code></pre>
That's right :) wanted to have it merged and fix in current development branch
@doucol

2022-08-30 23:22 UTC, doucol approved these changes

2022-08-30 23:22 UTC, merged