Fix formatting for spec.registry example
tigera/docs pull request #861
Opened 2023-08-11 01:59 UTC by KrisJohnstone

@tigera/docs,
Quick fix to indentation/formatting for the spec.registry example.

Product Version(s):
N/A - Just documentation fix.

DOCS review:
- [ ] A member of the docs team has approved this change.

Merge checklist:
N/A doco change.

2023-08-11 01:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tigera/docs?pullRequest=861) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tigera/docs?pullRequest=861) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tigera/docs?pullRequest=861) it.</sub>

2023-08-11 15:16 UTC, bmckercher123 commented
Thanks for taking the time to submit this fix. I'm assigning a Dev to review it and determine which other versions it applies to.

2023-08-11 15:19 UTC, bmckercher123 requested changes
Looks good. Please copy to fixes to calico (root), for 3.27 and 3.25.

2023-09-11 00:21 UTC, KrisJohnstone commented
*Bump*

2023-09-11 14:38 UTC, bmckercher123 commented
@KrisJohnstone You netlify has two dead links. I will fix them in /main and you can rebase so they pass.

2023-09-20 18:33 UTC, bmckercher123 approved these changes

2023-09-20 18:33 UTC, merged